development:
  adapter: postgresql
  encoding: utf8
  database: agendo_api_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: agendo_api_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: agendo_api_production
  pool: 5
  username: 
  password:
